# Generated by Django 5.0.6 on 2024-11-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eCount', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
